name: Tests
on: [push]
jobs:
    php-unit-and-functional-tests:
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: true
            matrix:
                php-versions: ['8.1']
        steps:
            # —— Setup Github actions —————————————————————————————————————————————
            # https://github.com/actions/checkout (official)
            - name: Git checkout placeholder-service
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  coverage: none
                  tools: composer:v2
                  extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
              env:
                  update: true

            #- name: Validate composer.json and composer.lock
            #  run: composer validate

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-
            - name: Install Composer dependencies
              run: composer install

            - name: Check the Symfony console
              run: bin/console -V
            # —— Code style —— (Based on this package: https://github.com/OskarStark/php-cs-fixer-ga)
            - name: PHP-CS-Fixer
              uses: docker://oskarstark/php-cs-fixer-ga
              with:
                  args: --diff --dry-run
            ## —— Tests ———————————————————————————————————————————————————————————
            - name: Run functionnal and unit tests
              run: |
                  composer test
